spring:
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/smartplace}
    username: ${AUTH_DB_USERNAME:smartplace}
    password: ${AUTH_DB_PASSWORD:smartplace_dev}

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        default_schema: auth
  flyway:
    enabled: true
    schemas:
      - auth
    default-schema: auth
    create-schemas: true
    locations:
      - classpath:db/migration
